#!/usr/bin/env bash
#
# A wizard — walks a human through deploying Twikoo (comment system) to Netlify.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

banner "Twikoo → Netlify 部署向导"

# ── Stage 1: MongoDB Atlas 数据库 ─────────────────────────────────────────
stage "MongoDB Atlas — 创建免费数据库"
say "Twikoo 的评论数据存在 MongoDB 里。先申请免费的 MongoDB Atlas 账号并建库。"
open_url "https://www.mongodb.com/cloud/atlas/register"
step "注册/登录 MongoDB Atlas（用邮箱即可，免费）"
pause "注册完成后回车继续"
step "创建免费集群 M0（FREE 档），区域选 AWS / Oregon (us-west-2)"
step "在左侧 Database Access 点 Add New Database User："
step "  Authentication Method 选 Password，设置用户名和密码（建议点 Auto Generate 自动生成强密码并妥善保存）"
step "  Database User Privileges 下 Add Built In Role，选 Atlas Admin，最后 Add User"
step "在左侧 Network Access 点 Add IP Address：Access List Entry 填 0.0.0.0/0（允许所有 IP，Netlify 出口不固定），Confirm"
step "在 Database 页面点 Connect → Drivers，复制连接字符串"
step "把字符串里的 <username>:<password> 替换为刚才设置的数据库用户名:密码"
say ""
note "连接字符串形如：mongodb+srv://user:pass@cluster0.xxxxx.mongodb.net/?retryWrites=true&w=majority"
note "它含数据库密码，务必保密，下面输入时会隐藏显示"
ask_secret MONGODB_URI "粘贴处理好的 MongoDB 连接字符串:"
write_env MONGODB_URI "$MONGODB_URI"
pause "数据库就绪，回车进入下一步"

# ── Stage 2: fork twikoo-netlify 仓库 ─────────────────────────────────────
stage "GitHub — fork Twikoo Netlify 仓库"
say "把 Twikoo 的 Netlify 版源码 fork 到自己 GitHub 账号下，供 Netlify 导入。"
open_url "https://github.com/twikoojs/twikoo-netlify"
step "点击页面右上角 Fork 按钮"
step "Owner 选自己的账号，仓库名保持 twikoo-netlify 即可，Create fork"
pause "fork 完成后回车继续"

# ── Stage 3: Netlify 导入并部署 ───────────────────────────────────────────
stage "Netlify — 导入项目并部署"
say "在 Netlify 导入刚才 fork 的仓库，配置数据库环境变量后部署。"
open_url "https://app.netlify.com/start"
step "点 Add new site → Import an existing project"
step "点 Deploy with GitHub（若未授权，先授权 GitHub）"
step "选择你账号下的 twikoo-netlify 仓库"
step "在 Site settings 页面点 Add environment variables → New variable："
step "  Key 填 MONGODB_URI，Value 填刚才的数据库连接字符串"
step "点 Deploy 开始部署，等待 1-2 分钟构建完成"
pause "部署完成后回车继续"

# ── Stage 4: 设置站点名并验证 ─────────────────────────────────────────────
stage "Netlify — 站点名与验证"
say "给站点起个好记的名字，并确认云函数正常运行。"
open_url "https://app.netlify.com/"
step "进入刚创建的站点 → Site configuration → Change site name"
step "站点名建议形如 twikoo-mytwikoo（最终域名 https://twikoo-mytwikoo.netlify.app）"
pause "改完站点名回车继续"
step "浏览器打开：https://你的站点名.netlify.app/.netlify/functions/twikoo"
step "如果看到“Twikoo 云函数运行正常”提示，说明部署成功"
note "若提示错误，多半是 MONGODB_URI 没配好或网络白名单没加 0.0.0.0/0，回去检查 Stage 1/3"
pause "确认云函数运行正常后回车继续"

# ── Stage 5: 填写 envId 并写入配置 ────────────────────────────────────────
stage "配置 — 填写 Twikoo envId"
say "最后把云函数地址（envId）记下来，写入配置文件。"
ask TWIKOO_ENV_ID "粘贴完整 envId（https://你的站点名.netlify.app/.netlify/functions/twikoo）:"
write_env TWIKOO_ENV_ID "$TWIKOO_ENV_ID"
say "envId 已保存。请把 TWIKOO_ENV_ID 的值告诉 AI 助手，它会帮你写进博客配置并开启评论。"
note "也可以稍后自己打开 .env 查看该值。"
pause "完成，回车查看汇总"

finish
